[tool.poetry]
name = "opendoor"
version = "0.1.0"
description = ""
authors = ["Alisson"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
flet = "^0.19.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
